"use client";

import { BoardroomSession } from "@/lib/types";

interface Props {
  session: BoardroomSession;
}

function generateHTML(session: BoardroomSession): string {
  const advisorSections = session.advisors
    .map((advisor) => {
      const pos = session.positions.find((p) => p.advisorId === advisor.id);
      const reb = session.rebuttals.find((r) => r.advisorId === advisor.id);
      const escapedPosContent = (pos?.content || "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/\n/g, "<br>");
      const escapedRebContent = (reb?.content || "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/\n/g, "<br>");

      return `
      <div class="advisor-card">
        <h3>${advisor.name} <span class="role">${advisor.role}</span></h3>
        <div class="answers">
          <div><strong>R1:</strong> ${pos?.answer || "—"}</div>
          <div><strong>Final:</strong> ${reb?.finalAnswer || "—"}</div>
          ${reb?.answerChanged ? '<span class="changed">CHANGED</span>' : ""}
        </div>
        <details>
          <summary>Round 1 Position</summary>
          <div class="content">${escapedPosContent}</div>
        </details>
        <details>
          <summary>Round 2 Rebuttal</summary>
          <div class="content">${escapedRebContent}</div>
        </details>
      </div>`;
    })
    .join("\n");

  const tableRows = session.advisors
    .map((advisor) => {
      const pos = session.positions.find((p) => p.advisorId === advisor.id);
      const reb = session.rebuttals.find((r) => r.advisorId === advisor.id);
      return `<tr>
        <td>${advisor.name}</td>
        <td class="answer">${pos?.answer || "—"}</td>
        <td class="answer ${reb?.answerChanged ? "changed" : ""}">${reb?.finalAnswer || "—"}</td>
        <td>${reb?.answerChanged ? "Yes" : ""}</td>
      </tr>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Boardroom: ${session.question}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #1a1a2e; color: #f0f0f5; padding: 2rem; line-height: 1.6; }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { color: #d4a017; font-size: 1.75rem; margin-bottom: 0.5rem; }
  h2 { color: #f0f0f5; font-size: 1.25rem; margin: 2rem 0 1rem; border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 0.5rem; }
  .question { color: #94a3b8; font-size: 1rem; margin-bottom: 2rem; }
  table { width: 100%; border-collapse: collapse; background: #22223a; border-radius: 8px; overflow: hidden; margin-bottom: 2rem; }
  th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid rgba(255,255,255,0.08); }
  th { color: #94a3b8; font-weight: 500; font-size: 0.875rem; }
  .answer { color: #d4a017; font-size: 0.8rem; max-width: 300px; }
  .changed { color: #d4a017; font-weight: 600; }
  .advisor-card { background: #22223a; border: 1px solid rgba(255,255,255,0.08); border-radius: 8px; padding: 1.5rem; margin-bottom: 1rem; }
  .advisor-card h3 { font-size: 1.1rem; margin-bottom: 0.5rem; }
  .role { font-size: 0.75rem; color: #d4a017; background: rgba(212,160,23,0.15); padding: 2px 8px; border-radius: 4px; margin-left: 0.5rem; }
  .answers { margin-bottom: 1rem; font-size: 0.875rem; color: #94a3b8; }
  .answers div { margin-bottom: 0.25rem; }
  .answers strong { color: #f0f0f5; }
  details { margin-top: 0.5rem; }
  summary { cursor: pointer; color: #d4a017; font-size: 0.875rem; padding: 0.5rem 0; }
  .content { padding: 1rem 0; color: #94a3b8; font-size: 0.875rem; }
  .footer { text-align: center; margin-top: 3rem; color: #94a3b8; font-size: 0.75rem; }
</style>
</head>
<body>
<div class="container">
  <h1>Boardroom</h1>
  <p class="question">${session.question}</p>

  <h2>Answer Tracker</h2>
  <table>
    <thead><tr><th>Advisor</th><th>Round 1</th><th>Final</th><th>Changed?</th></tr></thead>
    <tbody>${tableRows}</tbody>
  </table>

  <h2>Advisor Positions & Rebuttals</h2>
  ${advisorSections}

  <p class="footer">Generated by Boardroom — ${new Date().toLocaleDateString()}</p>
</div>
</body>
</html>`;
}

export default function ExportButton({ session }: Props) {
  const handleExportHTML = () => {
    const html = generateHTML(session);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "boardroom-results.html";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJSON = () => {
    const json = JSON.stringify(session, null, 2);
    const blob = new Blob([json], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "boardroom-results.json";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex gap-2">
      <button
        onClick={handleExportHTML}
        className="px-4 py-2 text-sm border border-border-subtle text-muted rounded-lg hover:border-gold hover:text-gold transition-colors"
      >
        Export HTML
      </button>
      <button
        onClick={handleExportJSON}
        className="px-4 py-2 text-sm border border-border-subtle text-muted rounded-lg hover:border-gold hover:text-gold transition-colors"
      >
        Export JSON
      </button>
    </div>
  );
}
